"""Generate Migrations For Models

Revision ID: aa3cd7ca543f
Revises: 
Create Date: 2025-04-15 21:56:18.454135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3cd7ca543f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='group_schema'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='group_schema'
    )
    op.create_table('expense_credits',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('paid_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('paid_to', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_schema.groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_to'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='group_schema'
    )
    with op.batch_alter_table('expense_credits', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_expense_credits_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_schema_expense_credits_paid_by'), ['paid_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_schema_expense_credits_paid_to'), ['paid_to'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_schema.groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='group_schema'
    )
    with op.batch_alter_table('expenses', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_expenses_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_schema_expenses_user_id'), ['user_id'], unique=False)

    op.create_table('friends',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('friend_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
    schema='group_schema'
    )
    with op.batch_alter_table('friends', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_friends_friend_id'), ['friend_id'], unique=False)

    op.create_table('group_members',
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_schema.groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    schema='group_schema'
    )
    with op.batch_alter_table('group_members', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_group_members_user_id'), ['user_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('expense_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['group_schema.expenses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='group_schema'
    )
    with op.batch_alter_table('comments', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_comments_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_schema_comments_user_id'), ['user_id'], unique=False)

    op.create_table('expense_debits',
    sa.Column('expense_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['group_schema.expenses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['group_schema.users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id', 'user_id'),
    schema='group_schema'
    )
    with op.batch_alter_table('expense_debits', schema='group_schema') as batch_op:
        batch_op.create_index(batch_op.f('ix_group_schema_expense_debits_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_debits', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_expense_debits_user_id'))

    op.drop_table('expense_debits', schema='group_schema')
    with op.batch_alter_table('comments', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_schema_comments_expense_id'))

    op.drop_table('comments', schema='group_schema')
    with op.batch_alter_table('group_members', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_group_members_user_id'))

    op.drop_table('group_members', schema='group_schema')
    with op.batch_alter_table('friends', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_friends_friend_id'))

    op.drop_table('friends', schema='group_schema')
    with op.batch_alter_table('expenses', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_expenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_schema_expenses_group_id'))

    op.drop_table('expenses', schema='group_schema')
    with op.batch_alter_table('expense_credits', schema='group_schema') as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_schema_expense_credits_paid_to'))
        batch_op.drop_index(batch_op.f('ix_group_schema_expense_credits_paid_by'))
        batch_op.drop_index(batch_op.f('ix_group_schema_expense_credits_group_id'))

    op.drop_table('expense_credits', schema='group_schema')
    op.drop_table('users', schema='group_schema')
    op.drop_table('groups', schema='group_schema')
    # ### end Alembic commands ###
